/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/mug.glb -o src/app/component/Mug.tsx -r public 
*/
interface GLTFAction extends THREE.AnimationClip {}

import { Decal, useGLTF, useTexture } from "@react-three/drei";
import React, { useEffect } from "react";
import * as THREE from "three";
import { Material, Mesh, MeshBasicMaterial, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";
import { Prop } from "./CanMug";

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
  };
  materials: {
    mug: THREE.MeshStandardMaterial;
    printTable: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export const Mug: React.FC<Prop> = ({
  img,
  color,
  scale,
  position,
  ...props
}) => {
  const { nodes, materials, scene } = useGLTF("/mug.glb") as GLTFResult;
  const texture = useTexture(img);
  const colorrbg = new THREE.Color(color);
  useEffect(() => {
    if (scene) {
      scene.traverse((child) => {
        const meshChild = child as Mesh;

        if (meshChild.isMesh && meshChild.material) {
          if (Array.isArray(meshChild.material)) {
            meshChild.material.forEach((material) => {
              if (
                material instanceof MeshStandardMaterial ||
                material instanceof MeshBasicMaterial
              ) {
                material.color.set(colorrbg);
              }
            });
          } else {
            const material = meshChild.material as Material;
            if (
              material instanceof MeshStandardMaterial ||
              material instanceof MeshBasicMaterial
            ) {
              material.color.set(colorrbg);
            }
          }

          meshChild.castShadow = false;
          meshChild.receiveShadow = false;
        }
      });
    }
  }, [color]);
  let a;
  if (scale) {
    a = new THREE.Vector3(scale[0], scale[1], scale[2]);
  }
  let b;
  if (position) {
    b = new THREE.Vector3(position[0], position[1], position[2]);
  }
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh.geometry} material={materials.mug} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials.printTable}>
        <meshBasicMaterial transparent opacity={0} />
        <Decal debug position={b} rotation={[0, 0, 0]} scale={a}>
          <meshBasicMaterial
            map={texture}
            polygonOffset
            polygonOffsetFactor={-1}
          />
        </Decal>
      </mesh>
    </group>
  );
};

useGLTF.preload("/mug.glb");
