"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/phone.glb -o src/app/component/Phone.tsx -r public 
*/
import { Decal, useGLTF, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { Ref, useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { Material, Mesh, MeshBasicMaterial, MeshStandardMaterial } from "three";
import { GLTF } from "three-stdlib";
import { Prop } from "./CanMug";

interface GLTFAction extends THREE.AnimationClip {}

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
  };
  materials: {
    Default: THREE.MeshStandardMaterial;
    printTable: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export const Phone: React.FC<Prop> = ({
  img,
  color,
  scale,
  position,
  debug,
  ...props
}) => {
  const { nodes, materials, scene } = useGLTF("/phonerrr.glb") as GLTFResult;
  const texture = useTexture(img);
  const [rotationDirection, setRotationDirection] = useState(1);

  const decal: Ref<THREE.Group<THREE.Object3DEventMap>> | undefined =
    useRef(null);
  const colorrbg = new THREE.Color(color);
  let thedebug = true;
  if (debug === false) {
    thedebug = debug;
    useFrame((state, delta) => {
      if (decal.current) {
        decal.current.rotation.y += 0.0005 * rotationDirection;

        decal.current.rotation.x += 0.0001 * rotationDirection;
        decal.current.rotation.z += 0.0001 * rotationDirection;

        if (
          decal.current.rotation.y >= Math.PI / 6 ||
          decal.current.rotation.y <= -Math.PI / 6
        ) {
          setRotationDirection(-rotationDirection);
        }

        decal.current.rotation.x = THREE.MathUtils.clamp(
          decal.current.rotation.x,
          -Math.PI / 20,
          Math.PI / 20
        );

        decal.current.rotation.z = THREE.MathUtils.clamp(
          decal.current.rotation.z,
          -Math.PI / 50,
          Math.PI / 50
        );
      }
    });
  }
  useEffect(() => {
    if (scene) {
      scene.traverse((child) => {
        const meshChild = child as Mesh;

        if (meshChild.isMesh && meshChild.material) {
          if (Array.isArray(meshChild.material)) {
            meshChild.material.forEach((material) => {
              if (
                material instanceof MeshStandardMaterial ||
                material instanceof MeshBasicMaterial
              ) {
                material.color.set(colorrbg);
              }
            });
          } else {
            const material = meshChild.material as Material;
            if (
              material instanceof MeshStandardMaterial ||
              material instanceof MeshBasicMaterial
            ) {
              material.color.set(colorrbg);
            }
          }

          meshChild.castShadow = false;
          meshChild.receiveShadow = false;
        }
      });
    }
  }, [color]);
  let a, b;
  if (position) {
    a = new THREE.Vector3(position[2], position[1], position[0]);
  }
  if (scale) {
    b = new THREE.Vector3(scale[0], scale[1], scale[2]);
  }
  return (
    <group ref={decal} {...props} dispose={null}>
      <mesh
        geometry={nodes.Mesh.geometry}
        material={materials.Default}
        scale={[5, 5, 5]}
      />
      <mesh
        geometry={nodes.Mesh_1.geometry}
        material={nodes.Mesh_1.material}
        scale={[5, 5, 5]}
      />
      <mesh
        geometry={nodes.Mesh_2.geometry}
        material={materials.printTable}
        scale={[5, 5, 5]}
      >
        <meshBasicMaterial transparent opacity={0} />
        <Decal
          debug={thedebug} //to remove the wireframes set to false
          position={a}
          rotation={[0, 1.5, 0.03]}
          scale={b}
        >
          <meshBasicMaterial
            map={texture}
            polygonOffset
            polygonOffsetFactor={-1}
          />
        </Decal>
      </mesh>
    </group>
  );
};

useGLTF.preload("/phonerrr.glb");
